[package]
name = "scout-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scout-parser = { path = "../scout-parser/" }
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.19.0"
