[package]
name = "scout-parser"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scout-lexer = { path = "../scout-lexer/" }

[dev-dependencies]
test-case = "*"
